### PR TITLE
Update process management with prod and dev

### PR DESCRIPTION
**Pull request by Pistus**
Add pm2 ecosystemfile with prod and dev environments.
Changed npm start to run bot in production mode
Changed npm run dev to run bot in development mode including watching /source folder

### CODE REVIEW

**Comment by bookercodes** [comment]
Feels like Christmas, thank you for another pull request 🎅

I am not too experienced with PM2. Before I spend too much time understanding this PR, can you tell me the advantages? Especially in development. 

At a glance, I think distinguishing `npm start` and `npm dev` makes sense 👍🏻

That being said, I am pretty happy developing with `node source/index.js`.

**Comment by Pistus** [comment]
The motivation is to make it easy for someone not familiar with the repo to start the service in prod and dev mode. It also makes it more similar to our other repos. For local development I like that the process runs in the background, auto-reloads on file changes and has logs with timestamps.

A little intro to the PM2 environment file:
```javascript
{
	"apps": [{ 
		"name": "discord-bot", // set the pm2 name -  would be index.js without this
		"wait_ready": true, // not needed really, but it adds a little delay before PM2 considers the service to be running
		"time": true, // Add a timestamp for error and log output
		"log_date_format": "DD-MM-YYYY HH:mm:ss.SSS", // define how the timestamp should be
		"script": "./source/index.js", // The entrypoint / file to run for the service
		"env": { // default settings and environment variables to add
			"NODE_ENV": "production"
		}, // environment specific settings / variables to add 
		"env_development": {
			"NODE_ENV": "development",
			"watch": ["./source"], // watch for file changes in the ./source folder
			"DEBUG_HIDE_DATE": true, // copy-paste leftover -> disable timestamp when using the debug package
			"DEBUG_COLORS": true, // copy-paste leftover -> show colors for express logs 
			"DEBUG_DEPTH": 2 //  copy-paste leftover -> express object inspection max depth
		}
	}]
}
```

**Review by codeluggage — CHANGES_REQUESTED** [review]
Worked well for me in local dev 👍 

Will need `pm2` installed on the server for `npm start` to work, so merging this as-is would break the bot. 

I like self contained dependencies better than relying on global packages to be installed, but it does fracture the `pm2` versions we use across different things, so there are tradeoffs. 

For this project I'm leaning towards making `pm2` a dependency so it can run easily for us or others that fork this.

**Review by codeluggage — APPROVED** [review]
Beautiful!

**Pull request merged**
